from flask import Flask

# CREATE AN INSTANCE OF THE FLASK CLASS

app = Flask(__name__)


# TO RUN THE APP
if __name__ == '__main__':
    # RUN FUNCTION TO EXECUTE THE APP
    # DEBUD IS TRUE TO ENABLE SOME DEBUG FUNCTIONALITIES
    # THUS THE SERVER WILL START
    # ALTHOUGH UPTILL HERE WITHOUT ANY |----ROUTER----| 
    # THE WEB BROWSER DOESN'T KNOW WHERE TO GO
    # THUS, THE BROWSER WILL SHOW NO URL FOUND    
    app.run(debug=True)

